### ISSUE TITLE
Compatibility with Umbrella Apps

### ISSUE THREAD

**Issue by GustavoZiaugra** [dariodf/lcov_ex#2]
Hello,
I am doing some tests to generate a set of LCOV files in an umbrella application and I see that there is confusion regarding the paths when generating them. Is your library compatible with umbrella applications today?

For example: 
When I run from the root path, all files get cover details from other apps, even don't have direct associations.

Thank you!

**Comment by dariodf** [comment]
Hello Gustavo,

I have used it in umbrella apps, but adding the dependency and configuration in the individual apps `mix.exs` file. You could do that for now as a workaround.

I'll leave this issue open as a request to avoid repeating the configuration each app of an umbrella.

**Comment by dariodf** [comment]
`mix lcov` now runs correctly for umbrella projects in version `0.2.2`.
